INSERT INTO EMPLOYEES (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, SOME_DATE, SOME_TIME, SOME_DATETIME, ACTIVE)
VALUES (1, 'Nikki Nicholas', 'Domingo', 'Romero', 15000, '2020-07-01', '04:18:39', '2020-07-01 04:18:39', true);

INSERT INTO EMPLOYEES (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, SOME_DATE, SOME_TIME, SOME_DATETIME, ACTIVE)
VALUES (2, 'Leslie Anne', 'Sayin', 'Romero', 17000, CURRENT_DATE(), CURRENT_TIME(), CURRENT_TIMESTAMP(), true);

INSERT INTO EMPLOYEES (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, SOME_DATE, SOME_TIME, SOME_DATETIME, ACTIVE)
VALUES (3, 'Maven Claire', 'Sayin', 'Romero', 13000, CURRENT_DATE(), CURRENT_TIME(), CURRENT_TIMESTAMP(), true);

INSERT INTO EMPLOYEES (ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, SOME_DATE, SOME_TIME, SOME_DATETIME, ACTIVE)
VALUES (4, 'Megan Claire', 'Sayin', 'Romero', 12000, CURRENT_DATE(), CURRENT_TIME(), CURRENT_TIMESTAMP(), true);
