INSERT INTO USER_ACCOUNTS (ID, EMAIL_ADDRESS, STATUS)
VALUES (1, 'registered@email.com', 'REGISTERED');

INSERT INTO USER_ACCOUNTS (ID, EMAIL_ADDRESS, STATUS)
VALUES (2, 'activated@email.com', 'ACTIVATED');

INSERT INTO USER_ACCOUNTS (ID, EMAIL_ADDRESS, STATUS)
VALUES (3, 'deactivated@email.com', 'DEACTIVATED');
