DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
  ID int NOT NULL,
  FIRST_NAME varchar(255) DEFAULT NULL,
  MIDDLE_NAME varchar(255) DEFAULT NULL,
  LAST_NAME varchar(255) DEFAULT NULL,
  SALARY decimal(10,0) DEFAULT NULL,
  SOME_DATE date DEFAULT NULL,
  SOME_TIME time DEFAULT NULL,
  SOME_DATETIME datetime DEFAULT NULL,
  ACTIVE tinyint(1) DEFAULT NULL,
  PRIMARY KEY (ID)
);
